### ISSUE TITLE
data migration bug

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#268]
@vshiray reported:

> I have a problem with data migration:
> [bbfs@swift1 var]$ fix_content_data backup.data fixed.data
> /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/log.rb:112:in `init': undefined method`each' for nil:NilClass (NoMethodError)
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/log.rb:125:in `warning'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/content_data/content_data.rb:192:in `add_instance'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/content_data/content_data.rb:577:in `read_old_instances_chunk'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/content_data/content_data.rb:517:in `block in from_file_old'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/content_data/content_data.rb:476:in `open'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/lib/content_data/content_data.rb:476:in `from_file_old'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/gems/content_server-1.7.0/bin/fix_content_data:10:in `<top (required)>'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/bin/fix_content_data:23:in `load'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/bin/fix_content_data:23:in `<main>'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/bin/ruby_executable_hooks:15:in `eval'
> - from /usr/local/rvm/gems/ruby-2.1.1@bbfs/bin/ruby_executable_hooks:15:in `<main>'

**Comment by genadyp** [comment]
@vshiray 
@kolmanv 
@yarondbb 
@AlexeyNemytov 

Problems:
1.No Params.init run while Log suppose that Params were initialized.
Solution: fixed in fix_content_data
2.There is no check of an instance line that was read from old-format file.
Solution: check was added
3.We suppose that delimiter in the old format files is a [comma](https://github.com/bbfsdev/bbfs/blob/master/lib/content_data/content_data.rb#L566), but actually, in this specific case '<' was used as a delimiter.
Solution: additional parameter, that contains fields delimiter was added to fix_content_data executable and appropriate methods of ContentData. Default value was set to comma.
4. Params.init no more demands from user an input.
Motivation: there are a number of executables  and tests that use Params.init but have no ARGV array.
5. command line help was added for bin/fix_content_data

**Comment by genadyp** [comment]
fixed :) fix_content_data successfully finished

> [genadyp@f1 bbfs]$ time ruby -Ilib bin/fix_content_data  ~/backup.data-20140324  ~/fixed.cd '<'
> real    9m38.932s
> user    9m34.136s
> sys     0m4.247s
> [genadyp@f1 bbfs]$  ls -lh ~/fixed.cd
> -rw-rw-r-- 1 genadyp genadyp 16M May 26 22:15 /home/genadyp/fixed.cd

Note the running time on the file with 308989 contents.
